In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
 from sklearn.ensemble import RandomForestRegressor

In [13]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    'criterion': ['squared_error', 'absolute_error'],
    'max_features': ['sqrt', 'log2'],
    'n_estimators': [10, 100]
}

grid = GridSearchCV(RandomForestRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [14]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R² score value for best parameters {}:".format(grid.best_params_, r_score))

The R² score value for best parameters {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}:

In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.134267,0.032548,0.041400,0.021229,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.808620,0.743667,0.808035,0.805433,0.724292,0.778010,0.036484,7
1,0.466463,0.036133,0.021876,0.007655,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.805956,0.764152,0.836392,0.830338,0.758648,0.799097,0.032469,3
2,0.103121,0.042618,0.000000,0.000000,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.786339,0.755239,0.816481,0.804224,0.735441,0.779545,0.030184,6
3,0.446201,0.009120,0.018749,0.006249,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.807015,0.776307,0.841672,0.830161,0.766317,0.804294,0.029323,1
4,0.143745,0.024999,0.000000,0.000000,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.772241,0.757272,0.796944,0.800498,0.730880,0.771567,0.025850,8
5,1.269134,0.026732,0.020685,0.015173,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.796564,0.770314,0.839194,0.822002,0.765572,0.798729,0.028603,4
6,0.131247,0.012500,0.003125,0.006250,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.772207,0.760124,0.824794,0.812922,0.740354,0.782080,0.031926,5
7,1.109647,0.111059,0.021876,0.007653,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.803911,0.776169,0.841055,0.823805,0.765353,0.802059,0.028336,2

In [18]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 35
BMI: 45
Children: 5
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 0

In [19]:
Future_Prediction = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[17291.0063148]