In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset = dataset.astype(int)

In [5]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
 from sklearn.ensemble import RandomForestRegressor

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    'criterion': ['squared_error', 'absolute_error'],
    'max_features': ['sqrt', 'log2'],
    'n_estimators': [10, 100]
}

grid = GridSearchCV(RandomForestRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [11]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R² score value for best parameters {}:".format(grid.best_params_, r_score))

The R² score value for best parameters {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}:

In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.074998,0.020729,0.000000,0.000000,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.788035,0.768961,0.804015,0.795482,0.708314,0.772961,0.034334,8
1,0.433236,0.006640,0.024999,0.007653,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.807739,0.755758,0.835905,0.827283,0.746092,0.794555,0.036902,4
2,0.094160,0.046326,0.006251,0.007656,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.801547,0.743722,0.818217,0.775451,0.751417,0.778071,0.028496,7
3,0.435279,0.011806,0.018750,0.006250,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.815452,0.761374,0.826870,0.823901,0.758494,0.797218,0.030685,3
4,0.118825,0.008521,0.000600,0.001199,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.788253,0.768028,0.846629,0.808846,0.725760,0.787503,0.040357,5
5,1.107904,0.010897,0.023662,0.006445,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.799786,0.773817,0.840587,0.826849,0.760489,0.800305,0.030379,2
6,0.113291,0.006003,0.006251,0.007655,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.797114,0.774833,0.804128,0.797749,0.740512,0.782867,0.023388,6
7,0.982699,0.148813,0.022841,0.012162,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.806583,0.778895,0.839854,0.823076,0.760271,0.801736,0.028889,1

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 24
BMI: 32
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [15]:
Future_Prediction = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[44644.13]